# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/fpga/xilinix/projects/seven_seg/seven_seg.cache/wt [current_project]
set_property parent.project_path D:/fpga/xilinix/projects/seven_seg/seven_seg.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib D:/fpga/xilinix/projects/seven_seg/seven_seg.srcs/sources_1/new/seven_seg_counter.vhd
read_xdc D:/fpga/xilinix/projects/seven_seg/seven_seg.srcs/constrs_1/imports/projects/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/fpga/xilinix/projects/seven_seg/seven_seg.srcs/constrs_1/imports/projects/Basys3_Master.xdc]

catch { write_hwdef -file seven_seg_counter.hwdef }
synth_design -top seven_seg_counter -part xc7a35tcpg236-1
write_checkpoint -noxdef seven_seg_counter.dcp
catch { report_utilization -file seven_seg_counter_utilization_synth.rpt -pb seven_seg_counter_utilization_synth.pb }
